name: Actions

on:
  push:
    branches:
      - production

jobs:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  tts-daemon:
    name: 'Docker Build - daemon'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@master
        with:
          push: true
          context: ./daemon
          file: ./daemon/Dockerfile
          tags: ghcr.io/carrismetropolitana/tts-daemon:${{ github.ref_name }}

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  tts-lib:
    name: 'Publish to NPM - lib'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup NodeJS
        uses: actions/setup-node@main
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM dependencies
        run: npm install
        working-directory: ./lib

      - name: Bump package version
        run: npx @helperkits/bumper bump
        working-directory: ./lib

      - name: Build package
        run: npm run build
        working-directory: ./lib

      - name: Publish package to NPM
        run: npm publish --access public
        working-directory: ./lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
